eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: user-service  
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.98.167.89/xiangshan?useSSL=false&characterEncoding=utf8
    username: root
    password: zy139

server:
  port: 8084